// <auto-generated />
using System;
using DevKitPage.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevKitPage.Infrastructure.Migrations
{
    [DbContext(typeof(DevKitPageDb))]
    [Migration("20261003232112_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DevKitPage.Core.EventoDeUso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecebidoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessaoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmUtc");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("MaquinaId", "EmUtc");

                    b.ToTable("EventosDeUso", (string)null);
                });

            modelBuilder.Entity("DevKitPage.Core.Maquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChaveHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaquinaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistradaEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoEnvioEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersaoDevKit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChaveHash")
                        .IsUnique();

                    b.HasIndex("MaquinaId")
                        .IsUnique();

                    b.ToTable("Maquinas", (string)null);
                });

            modelBuilder.Entity("DevKitPage.Core.TotalDiario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("TEXT");

                    b.Property<long>("Eventos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Dia");

                    b.HasIndex("MaquinaId", "Dia", "Tipo", "Detalhe")
                        .IsUnique();

                    b.ToTable("TotaisDiarios", (string)null);
                });

            modelBuilder.Entity("DevKitPage.Core.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BloqueadoAteUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeveTrocarSenha")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EhAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FalhasSeguidas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("DevKitPage.Core.EventoDeUso", b =>
                {
                    b.HasOne("DevKitPage.Core.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("DevKitPage.Core.TotalDiario", b =>
                {
                    b.HasOne("DevKitPage.Core.Maquina", null)
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
