// <auto-generated />
using System;
using DevKitPage.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevKitPage.Infrastructure.Migrations
{
    [DbContext(typeof(DevKitPageDb))]
    [Migration("20261007215156_GruposDeErro")]
    partial class GruposDeErro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DevKitPage.Core.EventoDeUso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecebidoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessaoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmUtc");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("MaquinaId", "EmUtc");

                    b.ToTable("EventosDeUso", (string)null);
                });

            modelBuilder.Entity("DevKitPage.Core.GrupoDeErro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Assinatura")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimeiraVersao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PrimeiroVistoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvidoNaVersao")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimaVersao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimoVistoEmUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Assinatura")
                        .IsUnique();

                    b.HasIndex("UltimoVistoEmUtc");

                    b.ToTable("GruposDeErro", (string)null);
                });

            modelBuilder.Entity("DevKitPage.Core.Maquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChaveHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaquinaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistradaEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoEnvioEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersaoDevKit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChaveHash")
                        .IsUnique();

                    b.HasIndex("MaquinaId")
                        .IsUnique();

                    b.ToTable("Maquinas", (string)null);
                });

            modelBuilder.Entity("DevKitPage.Core.OcorrenciaDeErro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("GrupoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trace")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersaoDevKit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmUtc");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("GrupoId", "EmUtc");

                    b.ToTable("OcorrenciasDeErro", (string)null);
                });

            modelBuilder.Entity("DevKitPage.Core.PedidoDeDemonstracao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ConsentimentoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecebidoEmUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecebidoEmUtc");

                    b.ToTable("PedidosDeDemonstracao", (string)null);
                });

            modelBuilder.Entity("DevKitPage.Core.TotalDiario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("TEXT");

                    b.Property<long>("Eventos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Dia");

                    b.HasIndex("MaquinaId", "Dia", "Tipo", "Detalhe")
                        .IsUnique();

                    b.ToTable("TotaisDiarios", (string)null);
                });

            modelBuilder.Entity("DevKitPage.Core.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BloqueadoAteUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeveTrocarSenha")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EhAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FalhasSeguidas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("DevKitPage.Core.EventoDeUso", b =>
                {
                    b.HasOne("DevKitPage.Core.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("DevKitPage.Core.OcorrenciaDeErro", b =>
                {
                    b.HasOne("DevKitPage.Core.GrupoDeErro", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevKitPage.Core.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("DevKitPage.Core.TotalDiario", b =>
                {
                    b.HasOne("DevKitPage.Core.Maquina", null)
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
